CREATE TABLE IF NOT EXISTS categories (

    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (

    location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float NOT NULL,
    lon float NOT NULL
);

CREATE TABLE IF NOT EXISTS users (

    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (

    request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp NOT NULL,
    event_id integer NOT NULL,
    requester_id integer NOT NULL,
    status VARCHAR(64) NOT NULL,
    CONSTRAINT fk_request FOREIGN KEY (requester_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS events (

    event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id integer NOT NULL,
    confirmed_requests bigint[] NOT NULL,
    created_on timestamp NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date timestamp NOT NULL,
    initiator_id integer NOT NULL,
    location_id integer NOT NULL,
    paid bool NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp NOT NULL,
    request_moderation bool NOT NULL,
    state VARCHAR(64) NOT NULL,
    title VARCHAR(250) NOT NULL,
    views integer,
    CONSTRAINT fk_category_event FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT fk_initiator_event FOREIGN KEY (initiator_id) REFERENCES users (user_id),
    CONSTRAINT fk_location_event FOREIGN KEY (location_id) REFERENCES locations (location_id)

);

CREATE TABLE IF NOT EXISTS compilations (

    compilation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned bool NOT NULL,
    title VARCHAR(64) NOT NULL,
    event_list bigint[]
);
