CREATE TABLE IF NOT EXISTS categories (

    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS locations (

    location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float,
    lon float
);

CREATE TABLE IF NOT EXISTS users (

    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254),
    name VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS requests (

    request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp,
    event_id integer,
    requester_id integer,
    status VARCHAR(64),
    CONSTRAINT fk_request FOREIGN KEY (requester_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS events (

    event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000),
    category_id integer,
    confirmed_requests bigint[],
    created_on timestamp,
    description VARCHAR(7000),
    event_date timestamp,
    initiator_id integer,
    location_id integer,
    paid bool,
    participant_limit integer,
    published_on timestamp,
    request_moderation bool,
    state VARCHAR(64),
    title VARCHAR(250),
    views integer,
    CONSTRAINT fk_category_event FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT fk_initiator_event FOREIGN KEY (initiator_id) REFERENCES users (user_id),
    CONSTRAINT fk_location_event FOREIGN KEY (location_id) REFERENCES locations (location_id)

);

CREATE TABLE IF NOT EXISTS compilations (

    compilation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned bool,
    title VARCHAR(64),
    event_list bigint[]
);
