CREATE TABLE IF NOT EXISTS endpoint_hit (
    endpoint_hit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(64) NOT NULL,
    uri VARCHAR(128) NOT NULL,
    ip VARCHAR(64) NOT NULL,
    time_created timestamp
);

